version: '2.2'
services:

        logstash:
    image: docker.elastic.co/logstash/logstash:7.12.1
    user: root
    container_name: logstash
    #depends_on: {"es01": {"condition": "service_healthy"}}
    volumes:
       - /home/ubuntu/elk_logstash/Kaggle/unbalaced_20_80_dataset.csv:/usr/share/logstash/Kaggle/unbalaced_20_80_dataset.csv
       - ./logstash_pipeline/:/etc/logstash/conf.d/
       - ./logstash_config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
       - ./logstash_config/logstash.yml:/usr/share/logstash/config/logstash.yml
    environment:
        SERVERNAME: localhost
        # ELASTICSEARCH_URL: http://es01:9200
        # ELASTICSEARCH_HOSTS: http://es01:9200
        LOG_LEVEL: debug
        # path.config: /etc/logstash/conf.d/
        path.settings: /usr/share/logstash/config
        
    ports:
        - 5044:5044
        - 9600:9600  
    networks:
        - elastic

volumes:
  data01:
    driver: local


networks:
  elastic:
    driver: bridge
